dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
cache:
  - pip: true
  - directories: libs/python-mapnik/build
services:
  - postgresql
  - redis-server
env:
  SETTINGS: ../tests/settings.py
addons:
  postgresql: 10
  apt:
    packages:
      - libmapnik-dev
      - libboost-all-dev
      - python3-dev
      - libcairo2
      - libcairo2-dev
      - postgresql-10-postgis-2.4
      - osm2pgsql
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -r requirements.txt
  - python app/cli/pymapnik.py install
before_script:
  - flask postgres init
  - flask osm init --osm_dump_file=europe/albania-latest.osm.pbf
script:
  - python -m pytest -s tests/
