dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
services:
  - postgresql
env:
  SETTINGS: ../tests/settings.py
addons:
  postgresql: 10
  apt:
    packages:
      - libmapnik-dev
      - libboost-all-dev
      - python3-dev
      - libcairo2
      - libcairo2-dev
      - postgresql-10-postgis-2.4
      - osm2pgsql
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -r requirements.txt
  - python app/cli/pymapnik.py install
before_script:
  - flask postgres init
script:
  - python -m pytest -s tests/
branches:
  only:
    - travis
