language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres

cache: pip

install:
  - git clone https://github.com/mapnik/mapnik.git --branch v3.0.x
  - cd mapnik
  - git submodule update --init
  - sudo python scons/scons.py install
  - cd ..
  - git clone https://github.com/mapnik/python-mapnik.git
  - cd python-mapnik
  - python setup.py install
  - pip install -r requirements.txt

script:
  - pylint src
  - SETTINGS=config/testing.py PYTHONPATH=src pytest

addons:
  apt:
    packages:
    - libharfbuzz-dev
    - libmapnik-dev

sudo: required