version: '3'

services:
  web:
    image: aktionskarten/backend:local
    build: .
    command: /source/docker/docker-entrypoint.sh
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=gis
      - SETTINGS=../docker/docker_settings.py
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - .:/source
  db:
    image: mdillon/postgis:9.6-alpine
    environment:
      - POSTGRES_DB=gis
