version: '3'

services:
  web:
    image: aktionskarten/backend:local
    build: .
    command: /source/docker/docker-entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_NAME=gis
      - DATABASE_URI=postgresql://postgres:@db/gis
      - MAPNIK_STYLESHEET_PATH=/opt/mapnik-stylesheets
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - mapnik-volume:/opt/mapnik-stylesheets
      - .:/source
  db:
    image: mdillon/postgis:9.6-alpine
    environment:
      - POSTGRES_DB=gis

volumes:
  mapnik-volume: