version: "3.9"
services:
  download-tiles:
    image: alpine:latest
    volumes:
      - ./data:/data
    command: >
      ash -c "cd /data && wget https://aktionskarten.github.io/tileserver-gl-data/tiles.mbtiles"
  clone-osm-bright:
    image: alpine/git:latest
    volumes:
      - ./data:/data
    command: 
      "clone https://github.com/aktionskarten/osm-bright-gl-style.git /data/osm-bright"
  tileserver-gl:
    image: kombinat451/tileserver-gl
    networks:
      - tiles
    depends_on:
      - download-tiles
      - clone-osm-bright
    ports:
      - "127.0.0.1:1312:80"
    volumes:
      - ./data:/data
  postgis:
    image: "postgis/postgis:13-3.1-alpine"
    networks:
      - database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - "postgis.env"
    ports:
      - "127.0.0.1:5432:5432"
  redis:
    image: "redis"
    networks:
      - redis
    ports:
      - "127.0.0.1:6379:6379"
  backend-tests:
    image: kombinat451/aktionskarten-backend-app
    networks:
      - tiles
      - database
      - redis
    depends_on:
      - tileserver-gl
      - postgis
      - redis
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - POSTGRES_HOST=postgis
      - REDIS_HOST=redis
      - TILESERVER_HOST=tileserver-gl
    env_file:
      - "postgis.env"
      - "backend.env"
    command: >
      sh -c "flask db upgrade &&
             python -m pytest -s tests/"

networks:
  tiles:
    name: tile_network
  database:
    name: database_network
  redis:
    name: redis_network
