version: "3.9"
services:
  tileserver-gl:
    image: "kombinat451/tileserver-gl"
    ports:
      - "127.0.0.1:1312:80"
    volumes:
      - ./data:/data
      - type: bind
        source: ${PWD}/tiles.mbtiles
        target: /data/tiles.mbtiles
  postgis:
    image: "postgis/postgis:13-3.1-alpine"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - "postgis.env"
    ports:
      - "127.0.0.1:5432:5432"
  redis:
    image: "redis"
    ports:
      - "127.0.0.1:6379:6379"
  backend:
    image: kombinat451/aktionskarten-backend-app
    depends_on:
      - tileserver-gl
      - postgis
      - redis
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - POSTGRES_HOST=postgis
      - REDIS_HOST=redis
      - TILESERVER_HOST=tileserver-gl:1312
    env_file:
      - "postgis.env"
      - "backend.env"
    command: python -m pytest -s tests/
