version: '3'

services:
  web:
    image: aktionskarten-backend-testing:0.1
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    environment:
      - PGUSER=postgres
      - PGHOST=db
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: mdillon/postgis:10-alpine
    environment:
      - POSTGRES_DB=gis
