version: '3'

services:
  web:
    image: aktionskarten-backend-testing:0.1
    build: .
    command: /source/docker/docker-entrypoint.sh
    environment:
      - PGUSER=postgres
      - PGHOST=db
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - .:/source
  db:
    image: mdillon/postgis:10-alpine
    environment:
      - POSTGRES_DB=gis
