version: '3'

services:
  backend:
    image: kombinat451/aktionskarten-backend-app:latest
    build:
      context: ../..
      dockerfile: deploy/docker/app/Dockerfile
    environment:
      - FLASK_ENV=testing
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis

  db:
    image: kombinat451/aktionskarten-backend-db:latest
    build:
      context: ../..
      dockerfile: deploy/docker/db/Dockerfile

  redis:
    image: redis
    expose:
      - 6379
