name: tests on docker
on: [push]

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and subrepos
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build docker image
        run: docker build -t kombinat451/aktionskarten-backend-app -f deploy/docker/app/Dockerfile .
      - name: Run tests
        run: docker-compose -f deploy/docker/docker-compose-test.yml run backend-tests
