name: tests on docker
on: [push]

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and subrepos
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build docker image
        run: docker build -t kombinat451/aktionskarten-backend-app -f deploy/docker/app/Dockerfile .
      - name: Download mbtiles
        run: wget https://aktionskarten.github.io/tileserver-gl-data/tiles.mbtiles
      - name: Start docker containers
        run: docker-compose -f deploy/docker/docker-compose.yml up
      - name: Run tests
        run: docker exec it backend-backend-1 python -m pytest -s tests/
