name: tests
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo and subrepos
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: kombinat451/aktionskarten-backend-app:latest
          file: deploy/docker/app/Dockerfile
      -
        name: Run tests
        run: docker-compose -f deploy/docker/test/docker-compose.yml run backend-tests
