name: github-actions
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout repo and subrepos
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install apt packages
        run: sudo apt-get install -y libmapnik-dev libboost-all-dev python3-dev libcairo2 libcairo2-dev fonts-noto
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip
        run: pip install -U pip
      - name: Install pytest
        run: pip install -U pytest
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Build pymapnik
        run: python app/cli/pymapnik.py install
      - name: Download mbtiles
        run: wget https://aktionskarten.github.io/tileserver-gl-data/tiles.mbtiles
      - name: Start docker container
        run: docker-compose up
      - name: Wait for database
        run: |
          while ! pg_isready -h postgis > /dev/null 2> /dev/null; do
            echo "Connecting to postgis Failed"
            sleep 1
          done
      - name: Upgrade DB
        run: flask db upgrade
      - name: Run tests
        run: python -m pytest -s tests/
